import { StyleSheet } from "react-native";

const homestyles = StyleSheet.create({
  popup2ItemContainer: {
    flex: 1,
    marginTop: 18,
    marginHorizontal: 5,
    alignItems: "center",
  },
  popup2ListContainer: {
    height: 400,
    marginTop: 360,
    marginHorizontal: 50,
    left: 12,
    zIndex: 21,
  },
  popup2textitle: {
    fontFamily: "P5-Font",
    fontSize: 11,
    color: "#fff",
    textAlign: "center",
    transform: [{ rotate: "-8deg" }],
    zIndex: 0,
    width: 115,
    top: 64,
    left: 2,
  },
  popup2cardnotch: {
    width: 130,
    height: 58,
    top: 27,
    zIndex: -1,
  },
  popup2cardpressable: {
    width: 80,
    height: 80,
  },
  popup2card: {
    width: 80,
    height: 80,
    top: 15,
    left: 3,
  },
  popup2view: {
    position: "absolute",
    backgroundColor: "transparent",
    width: "100%",
    height: "120%",
    left: -400,
    top: 20,
    zIndex: 20,
  },
  popup2: {
    position: "absolute",
    width: 390,
    height: 390,
    left: 2,
    top: 250,
    zIndex: 20,
  },
  popup2text: {
    fontFamily: "P5-Font",
    fontSize: 17,
    zIndex: 25,
    color: "#fff",
    position: "absolute",
    width: 180,
    height: 70,
    left: 158,
    top: 335,
    textAlign: "center",
  },
  popup2backpressable: {
    position: "absolute",
    left: 0,
    top: 0,
    zIndex: 25,
    transform: [{ rotate: "-3deg" }],
  },
  popup2back: {
    position: "absolute",
    width: 100,
    height: 70,
    left: 32,
    top: 323,
    zIndex: 25,
  },
  popupItemContainer: {
    flex: 1,
    marginTop: 18,
    marginHorizontal: 5,
    alignItems: "center",
  },
  popupListContainer: {
    height: 400,
    marginTop: 360,
    marginHorizontal: 55,
    left: 16,
    zIndex: 21,
  },
  popuptextitle: {
    fontFamily: "P5-Font",
    fontSize: 11,
    color: "#fff",
    textAlign: "center",
    transform: [{ rotate: "-8deg" }],
    zIndex: 0,
    width: 115,
    top: 25,
    left: 2,
  },
  popupcardnotch: {
    width: 130,
    height: 58,
    top: -12,
    zIndex: -1,
  },
  popupcardpressable: {
    width: 75,
    height: 150,
  },
  popupcard: {
    width: 75,
    height: 150,
    top: -20,
    left: 3,
  },
  popupview: {
    position: "absolute",
    backgroundColor: "transparent",
    width: "100%",
    height: "120%",
    left: 400,
    top: 20,
    zIndex: 20,
  },
  popup: {
    position: "absolute",
    width: 390,
    height: 390,
    left: 2,
    top: 250,
    zIndex: 20,
  },
  popuptext: {
    fontFamily: "P5-Font",
    fontSize: 17,
    zIndex: 25,
    color: "#fff",
    position: "absolute",
    width: 200,
    height: 45,
    left: 152,
    top: 335,
    textAlign: "center",
  },
  popupbackpressable: {
    position: "absolute",
    left: 0,
    top: 0,
    zIndex: 25,
    transform: [{ rotate: "-3deg" }],
  },
  popupback: {
    position: "absolute",
    width: 100,
    height: 70,
    left: 32,
    top: 323,
    zIndex: 25,
  },
  prioritybutton: {
    position: "relative",
    width: 65,
    height: 65,
    bottom: 65,
    left: 55,
    zIndex: 9,
    marginBottom: -65,
  },
  prioritybuttonpressable: {
    position: "relative",
    width: 65,
    height: 65,
    zIndex: 9,
  },
  hiddenpriority: {
    opacity: 0,
  },
  isfav: {
    position: "relative",
    width: 45,
    height: 45,
    bottom: 125,
    left: -58,
    zIndex: 9,
    marginBottom: -100,
  },
  hiddenFav: {
    opacity: 0,
  },
  welcome: {
    fontFamily: "P5-Font",
    fontSize: 25,
    color: "#000",
    textAlign: "center",
    zIndex: 7,
    width: 400,
    top: 55,
    left: -5,
  },
  welcome1: {
    fontFamily: "P5-Font",
    position: "absolute",
    fontSize: 25,
    color: "#c33333",
    textAlign: "center",
    zIndex: 6,
    width: 400,
    top: 56,
    left: -4,
  },
  welcome2: {
    fontFamily: "P5-Font",
    fontSize: 25,
    color: "#000",
    textAlign: "center",
    zIndex: 7,
    width: 400,
    top: 58,
    left: -5,
  },
  welcome3: {
    fontFamily: "P5-Font",
    position: "absolute",
    fontSize: 25,
    color: "#c33333",
    textAlign: "center",
    zIndex: 6,
    width: 400,
    top: 90.5,
    left: -4,
  },
  notecat: {
    width: 19,
    height: 19,
    transform: [{ rotate: "-15deg" }],
    top: -63,
    left: -51,
    zIndex: 4,
  },
  textcat: {
    fontFamily: "P5-Font",
    fontSize: 7.5,
    color: "#000",
    textAlign: "center",
    transform: [{ rotate: "-9deg" }],
    zIndex: 6,
    width: 80,
    top: -50.3,
    left: -22.3,
  },
  catListContainer: {
    height: 200,
    marginTop: 112,
    marginLeft: -2,
    zIndex: 8,
    transform: [{ rotate: "4deg" }],
  },
  catItemContainer: {
    margin: 3,
    alignItems: "center",
  },
  catTextitle: {
    fontFamily: "P5-Font",
    fontSize: 13,
    color: "#000",
    textAlign: "center",
    transform: [{ rotate: "-10deg" }],
    zIndex: 6,
    width: 80,
    top: 41.5,
    left: -3.5,
  },
  catNotch: {
    width: 85,
    height: 45,
    top: 9,
    left: -6,
    zIndex: 5,
  },
  catPressable: {
    width: 70,
    height: 70,
  },
  cat: {
    width: 60,
    height: 60,
    zIndex: 4,
  },
  selectedCat: {
    top: -30,
    left: -7,
    width: 78,
    height: 78,
  },
  selectedCatNotch: {
    top: -17,
    width: 100,
    height: 55,
  },
  selectedCatTextitle: {
    top: 22,
    fontSize: 16,
  },
  listContainer: {
    flex: 1,
    marginTop: -45,
    marginBottom: 0,
  },
  itemContainer: {
    flex: 1,
    marginTop: 18,
    alignItems: "center",
  },
  row: {
    flex: 1,
    justifyContent: "space-around",
  },
  textitle: {
    fontFamily: "P5-Font",
    fontSize: 14,
    color: "#fff",
    textAlign: "center",
    transform: [{ rotate: "-8deg" }],
    zIndex: 0,
    width: 125,
    top: 46,
    left: 2,
  },
  cardnotch: {
    width: 170,
    height: 68,
    top: 2,
    zIndex: -1,
  },
  cardpressable: {
    width: 126,
    height: 240,
  },
  card: {
    width: 126,
    height: 240,
    zIndex: 1,
    top: -29,
  },
  newnotepressable: {
    position: "absolute",
    left: 0,
    bottom: 0,
    zIndex: 3,
  },
  newnote: {
    position: "absolute",
    width: 125,
    height: 55,
    left: 18,
    bottom: 18,
    zIndex: 3,
  },
  delprofilepressable: {
    position: "absolute",
    right: 0,
    top: 0,
    zIndex: 3,
  },
  delprofile: {
    position: "absolute",
    width: 80,
    height: 85,
    right: 14,
    top: 45,
    zIndex: 3,
  },
  delcatpressable: {
    position: "absolute",
    right: 0,
    top: 0,
    zIndex: 3,
  },
  delcat: {
    position: "absolute",
    width: 80,
    height: 78,
    right: 158,
    top: 50,
    zIndex: 3,
    opacity: 0.5,
  },
  logoutpressable: {
    position: "absolute",
    left: 0,
    top: 0,
    zIndex: 3,
  },
  logout: {
    position: "absolute",
    width: 80,
    height: 80,
    left: 15,
    top: 50,
    zIndex: 3,
  },
  categoriesstrip: {
    position: "absolute",
    width: 400,
    height: 125,
    left: 0,
    top: 140,
    zIndex: 2,
  },
  header: {
    position: "absolute",
    width: 400,
    height: 400,
    left: 0,
    top: -12,
    zIndex: 1,
  },
  bg: {
    position: "absolute",
    width: 400,
    height: 830,
    left: 0,
    top: 60,
    zIndex: -2,
  },
  blackfade: {
    position: "absolute",
    width: 450,
    height: 900,
    left: 0,
    top: 0,
    zIndex: 9,
    opacity: 0,
    backgroundColor: "black",
  },
});

export default homestyles;
