import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  under: {
    backgroundColor: "#cc0f1e",
    position: "absolute",
    width: "100%",
    height: "20%",
    bottom: -140,
    zIndex: -7,
  },
  // TEXT INPUTS DE PRIMERO ACOMPAÑADOS POR SU FIELD RESPECTIVO
  input2: {
    fontFamily: "P5-Font",
    fontSize: 18,
    width: 150,       // Ancho fijo
    height: 40,       // Alto fijo
    padding: 10,
    backgroundColor: 'transparent',
    color: '#000',
  
  },
  fieldlogin1: {
    position: "absolute",
    width: 250,
    height: 55,
    left: 465,
    bottom: 300,
  },
  input1Login: {
    // Se pueden acortar en general quitando lo innecesario como el transform
    width: 250,
    height: 20,
    borderColor: "#ccc",
    left: 510,
    bottom: 340,
    transform: [{ translateX: -125 }, { translateY: -10 }],
    borderWidth: 0,
    paddingHorizontal: 10,
    color: "black", // Color del texto para que sea legible
    zIndex: 10,
    position: "absolute", // Asegúrate de que esté en posición absoluta
    backgroundColor: "transparent", // Fondo transparente
  },

  fieldlogin2: {
    position: "absolute",
    width: 250,
    height: 55,
    left: 465,
    bottom: 220,
  },
  input2Login: {
    fontFamily: "P5-Font",
    width: 250,
    height: 20,
    borderColor: "#ccc",
    left: 510,
    bottom: 260,
    transform: [{ translateX: -125 }, { translateY: -10 }],
    borderWidth: 0,
    paddingHorizontal: 10,
    color: "black", // Color del texto para que sea legible
    zIndex: 10,
    position: "absolute", // Asegúrate de que esté en posición absoluta
    backgroundColor: "transparent", // Fondo transparente
  },
  fieldregister1: {
    position: "absolute",
    width: 250,
    height: 55,
    left: 465,
    bottom: 330,
  },
  input1Register: {
    width: 250,
    height: 20,
    borderColor: "#ccc",
    left: 510,
    bottom: 370,
    transform: [{ translateX: -125 }, { translateY: -10 }],
    borderWidth: 0,
    paddingHorizontal: 10,
    color: "black", // Color del texto para que sea legible
    zIndex: 10,
    position: "absolute", // Asegúrate de que esté en posición absoluta
    backgroundColor: "transparent", // Fondo transparente
  },
  fieldregister2: {
    position: "absolute",
    width: 250,
    height: 55,
    left: 465,
    bottom: 260,
  },
  input2Register: {
    width: 250,
    height: 20,
    borderColor: "#ccc",
    left: 510,
    bottom: 300,
    transform: [{ translateX: -125 }, { translateY: -10 }],
    borderWidth: 0,
    paddingHorizontal: 10,
    color: "black", // Color del texto para que sea legible
    zIndex: 10,
    position: "absolute", // Asegúrate de que esté en posición absoluta
    backgroundColor: "transparent", // Fondo transparente
  },
  fieldregister3: {
    position: "absolute",
    width: 250,
    height: 55,
    left: 465,
    bottom: 190,
  },
  input3Register: {
    width: 250,
    height: 20,
    borderColor: "#ccc",
    left: 510,
    bottom: 230,
    transform: [{ translateX: -125 }, { translateY: -10 }],
    borderWidth: 0,
    paddingHorizontal: 10,
    color: "black", // Color del texto para que sea legible
    zIndex: 10,
    position: "absolute", // Asegúrate de que esté en posición absoluta
    backgroundColor: "transparent", // Fondo transparente
  },
  fieldforgot1: {
    position: "absolute",
    width: 250,
    height: 55,
    left: -435,
    bottom: 240,
  },
  input1Forgot: {
    width: 250,
    height: 20,
    borderColor: "#ccc",
    left: -380,
    bottom: 285,
    transform: [{ translateX: -125 }, { translateY: -10 }],
    borderWidth: 0,
    paddingHorizontal: 10,
    color: "black", // Color del texto para que sea legible
    zIndex: 10,
    position: "absolute", // Asegúrate de que esté en posición absoluta
    backgroundColor: "transparent", // Fondo transparente
  },
  fieldforgot2: {
    // Faltan crear los 3 estilos para los TextInput, preferiblemente más cortos
    position: "absolute",
    width: 250,
    height: 55,
    left: -835,
    bottom: 240,
  },
  fieldforgot3: {
    position: "absolute",
    width: 250,
    height: 55,
    left: -1235,
    bottom: 300,
  },
  fieldforgot4: {
    position: "absolute",
    width: 250,
    height: 55,
    left: -1235,
    bottom: 220,
  },
  sendbutton: {
    position: "absolute",
    width: 160,
    height: 70,
    left: -400,
    bottom: 105,
  },
  sendbuttonPressable: {
    position: "absolute",
    width: 160,
    height: 70,
    left: 0,
    bottom: 0,
  },
  verifybutton: {
    position: "absolute",
    width: 160,
    height: 70,
    left: -800,
    bottom: 105,
  },
  verifybuttonPressable: {
    position: "absolute",
    width: 160,
    height: 70,
    left: 0,
    bottom: 0,
  },
  confirmbutton: {
    position: "absolute",
    width: 160,
    height: 70,
    left: -1200,
    bottom: 105,
  },
  confirmbuttonPressable: {
    position: "absolute",
    width: 160,
    height: 70,
    left: 0,
    bottom: 0,
  },
  backtologin2: {
    position: "absolute",
    width: 130,
    height: 70,
    left: 130,
    bottom: -280,
  },
  backtologin2Pressable: {
    position: "absolute",
    width: 130,
    height: 70,
    left: 0,
    bottom: 0,
    transform: [{ rotate: "2deg" }],
  },
  forgottitle: {
    position: "absolute",
    width: 190,
    height: 90,
    left: -410,
    bottom: 380,
  },
  registerbutton: {
    position: "absolute",
    width: 160,
    height: 70,
    left: 105,
    bottom: -200,
  },
  registerbuttonPressable: {
    position: "absolute",
    width: 160,
    height: 70,
    left: 0,
    bottom: 0,
  },
  backtologin1: {
    position: "absolute",
    width: 130,
    height: 70,
    left: 130,
    bottom: -280,
  },
  backtologin1Pressable: {
    position: "absolute",
    width: 130,
    height: 70,
    left: 0,
    bottom: 0,
    transform: [{ rotate: "2deg" }],
  },
  starsplit1: {
    position: "absolute",
    width: 60,
    height: 60,
    left: 50,
    bottom: -280,
  },
  starsplit2: {
    position: "absolute",
    width: 60,
    height: 60,
    right: 50,
    bottom: -280,
  },
  registertitle: {
    position: "absolute",
    width: 160,
    height: 60,
    left: 505,
    bottom: 415,
  },
  book: {
    position: "absolute",
    width: 350,
    height: 420,
    left: 425,
    bottom: 155,
  },
  login: {
    position: "absolute",
    width: 150,
    height: 65,
    left: 508,
    bottom: 410,
  },
  loginbutton: {
    position: "absolute",
    width: 160,
    height: 70,
    left: 105,
    bottom: -200,
  },
  loginbuttonpressable: {
    position: "absolute",
    width: 160,
    height: 70,
    left: 0,
    bottom: 0,
  },
  register: {
    position: "absolute",
    width: 160,
    height: 55,
    right: 10,
    bottom: -280,
    transform: [{ rotate: "6deg" }],
  },
  registerPressable: {
    position: "absolute",
    width: 160,
    height: 55,
    right: 0,
    bottom: 0,
    transform: [{ rotate: "6deg" }],
    flex: 1,
  },
  forgot: {
    position: "absolute",
    width: 150,
    height: 70,
    left: 15,
    bottom: -282,
  },
  forgotPressable: {
    position: "absolute",
    width: 150,
    height: 70,
    left: 0,
    bottom: 0,
    transform: [{ rotate: "-7deg" }],
    zIndex: 1,
  },
  starsplit: {
    position: "absolute",
    width: 60,
    height: 60,
    left: 167,
    bottom: -280,
  },
  wyn: {
    position: "absolute",
    width: 220,
    height: 155,
    left: 5,
    top: -112,
    transform: [{ rotate: "5deg" }],
  },
  splash0: {
    position: "absolute",
    width: 150,
    height: 150,
    left: -60,
    bottom: 140,
    transform: [{ rotate: "-70deg" }],
  },
  splash1: {
    position: "absolute",
    width: 150,
    height: 150,
    left: -55,
    top: 315,
    transform: [{ rotate: "-70deg" }],
  },
  splash2: {
    position: "absolute",
    width: 200,
    height: 150,
    left: -100,
    bottom: -40,
    transform: [{ rotate: "-40deg" }],
  },
  splash3: {
    position: "absolute",
    width: 200,
    height: 150,
    right: -115,
    bottom: 170,
    transform: [{ rotate: "-30deg" }],
  },
  splash4: {
    position: "absolute",
    width: 200,
    height: 150,
    right: -60,
    bottom: -75,
    transform: [{ rotate: "130deg" }],
  },
  splash5: {
    position: "absolute",
    width: 200,
    height: 150,
    right: -80,
    top: 250,
    transform: [{ rotate: "130deg" }],
  },
  splash6: {
    position: "absolute",
    width: 200,
    height: 150,
    left: -65,
    top: 160,
    transform: [{ rotate: "30deg" }],
  },
  tap: {
    position: "absolute",
    width: 275,
    height: 60,
    left: 60,
    bottom: 320,
    zIndex: 1,
  },
  logo: {
    position: "absolute",
    width: 330,
    height: 200,
    left: 25,
    top: 55,
    zIndex: 1,
  },
  starsbg: {
    position: "absolute",
    width: 395,
    height: 500,
    left: 0,
    top: -199,
  },
  splitstripe: {
    position: "absolute",
    width: 420,
    height: 220,
    left: -12,
    top: 230,
    transform: [{ rotate: "-3deg" }],
    zIndex: 1,
  },
  ptbg: {
    position: "absolute",
    width: 700,
    height: 700,
    left: -155,
    bottom: -30,
    opacity: 0.6,
  },
  rights: {
    position: "absolute",
    width: 180,
    height: 60,
    left: 12,
    bottom: 15,
  },
  blackfade: {
    position: "absolute",
    width: 450,
    height: 900,
    left: 0,
    top: 0,
    zIndex: 15,
    opacity: 0,
    backgroundColor: "black",
  },
  container: {
    flex: 1,
    backgroundColor: "#080808",
    zIndex: 4,
  },
  Loading1: {
    position: "absolute",
    width: 180,
    height: 180,
    right: 10,
    bottom: 60,
  },
  Loading2: {
    position: "absolute",
    width: 160,
    height: 80,
    right: 15,
    bottom: -5,
  },
});

export default styles;
